### PR TITLE
On version 1.21.8, there was an error:

### PR DESCRIPTION
**Pull request by Haizenfell**
[01:01:34 ERROR]: Could not pass event PlayerInteractEvent to JukeboxExtendedReborn vdev java.lang.NoClassDefFoundError: Could not initialize class me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor
    at JEXT-Reborn_dev-shadowed.jar/me.spartacus04.jext.discs.DiscManager.mergedStop(DiscManager.kt:169) ~[JEXT-Reborn_dev-shadowed.jar:?]
    ...
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3 [in thread "Server thread"]
    at JEXT-Reborn_dev-shadowed.jar/me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.<clinit>(NBTEditor.java:51) ~[JEXT-Reborn_dev-shadowed.jar:?]
    ...
I updated NBTEditor to the latest version 7.19.10, and after that the plugin started working correctly.
Please update the plugin version so everyone can use it.

### CODE REVIEW

**Comment by Haizenfell** [comment]
If anyone needs a version for 1.21.8, here it is.
[JEXT-Reborn_dev-shadowed.zip](https://github.com/user-attachments/files/22748779/JEXT-Reborn_dev-shadowed.zip)
Now I'll see if it works on 1.21.9, if not, I'll try to add support
